<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.8.5 on darwin)" generated="20200925 11:20:11.713" rpa="false">
<suite id="s1" name="Shopping Cart Success" source="/Users/boyone/workspaces/sck/shopping-cart/atdd/ui/shopping_cart_success.robot">
<kw name="Open Browser" library="SeleniumLibrary" type="setup">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>${url}</arg>
<arg>gc</arg>
</arguments>
<msg timestamp="20200925 11:20:11.851" level="INFO">Opening browser 'gc' to base url 'http://localhost/Product-list'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<status status="FAIL" starttime="20200925 11:22:09.932" endtime="20200925 11:22:09.933"></status>
</kw>
<msg timestamp="20200925 11:22:09.933" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<status status="FAIL" starttime="20200925 11:20:11.850" endtime="20200925 11:22:09.933"></status>
</kw>
<test id="s1-t1" name="ซื้อสินค้า 1 ชิ้น เลือกจัดส่งแบบ kerry เลือกตัดเงินผ่าน บัตรเครดิต visa ได้รับ notofication ผ่าน in-app">
<tags>
<tag>robot:exit</tag>
</tags>
<status status="FAIL" starttime="20200925 11:22:09.934" endtime="20200925 11:22:09.942" critical="yes">Test execution stopped due to a fatal error.</status>
</test>
<kw name="Close Browser" library="SeleniumLibrary" type="teardown">
<doc>Closes the current browser.</doc>
<msg timestamp="20200925 11:22:09.944" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef61f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
<msg timestamp="20200925 11:22:09.944" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef6340&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
<msg timestamp="20200925 11:22:09.945" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef6490&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
<status status="PASS" starttime="20200925 11:22:09.943" endtime="20200925 11:22:09.951"></status>
</kw>
<status status="FAIL" starttime="20200925 11:20:11.715" endtime="20200925 11:22:09.951">Suite setup failed:
Execution terminated by signal</status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="0" info="combined" combined="NOT robot:exit">NOT robot:exit</stat>
<stat pass="0" fail="1">robot:exit</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="Shopping Cart Success">Shopping Cart Success</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200925 11:22:09.933" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<msg timestamp="20200925 11:22:09.944" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef61f0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
<msg timestamp="20200925 11:22:09.944" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef6340&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
<msg timestamp="20200925 11:22:09.945" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10bef6490&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/c3ab3164111d95a58ac36a6ee3877c26</msg>
</errors>
</robot>
